trigger: none

stages:
- template: templates/py-packaging-stage.yml
  parameters:
    enable_linux_cpu: false
    enable_linux_gpu: false
    enable_linux_gpu_training: false
    enable_linux_gpu_py35: false
    enable_windows_cpu: false
    enable_windows_gpu: true
    enable_mac_cpu: false
    enable_linux_arm: false
